Setting:
  Debug: false
  Lang: en
Worker:
  DateFormat: 'YYYY-MM-dd HH:mm:ss'
  Path: '/Workers'
  Reward:
    DayAmount: 10
    MonthAmount: 300
  Position:
    - Name: Builder
      GameMode: CREATIVE
      World:
      - world
    - Name: Moderator
      GameMode: SPECTATOR
      World:
      - world