name: SalariesMe
version: 0.0.1
author: clo5de
main: tw.at.clo5de.SalariesMe
depend: [ Vault, GroupManager ]
commands:
  sm:
    description: SalariesMe command
    usage: /sm [args]
  SalariesMe:
    description: SalariesMe command
    usage: /sm [args]